// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecallOperations.Api.Data;

#nullable disable

namespace RecallOperations.Api.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260929102509_RemoveUnusedDepartments")]
    partial class RemoveUnusedDepartments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleRecall.Shared.Models.RecallCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("KS_RecallCustomers", "dbo");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "arjun.sharma@example.com",
                            FullName = "Arjun Sharma"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "priya.reddy@example.com",
                            FullName = "Priya Reddy"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "rahul.verma@example.com",
                            FullName = "Rahul Verma"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "sneha.patel@example.com",
                            FullName = "Sneha Patel"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "vikram.nair@example.com",
                            FullName = "Vikram Nair"
                        },
                        new
                        {
                            CustomerId = 6,
                            Email = "ananya.rao@example.com",
                            FullName = "Ananya Rao"
                        },
                        new
                        {
                            CustomerId = 7,
                            Email = "rohit.kumar@example.com",
                            FullName = "Rohit Kumar"
                        },
                        new
                        {
                            CustomerId = 8,
                            Email = "meera.iyer@example.com",
                            FullName = "Meera Iyer"
                        },
                        new
                        {
                            CustomerId = 9,
                            Email = "aditya.singh@example.com",
                            FullName = "Aditya Singh"
                        },
                        new
                        {
                            CustomerId = 10,
                            Email = "kavya.menon@example.com",
                            FullName = "Kavya Menon"
                        });
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.RecallCustomerVehicle", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("CustomerId", "Vin");

                    b.HasIndex("Vin");

                    b.ToTable("KS_CustomerVehicles", "dbo");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Vin = "1HGCM82633A123456"
                        },
                        new
                        {
                            CustomerId = 2,
                            Vin = "5YFBURHE5FP123457"
                        },
                        new
                        {
                            CustomerId = 3,
                            Vin = "1C4RJFAG5FC123458"
                        },
                        new
                        {
                            CustomerId = 4,
                            Vin = "3FA6P0H76KR123459"
                        },
                        new
                        {
                            CustomerId = 5,
                            Vin = "JM1BL1SF8A1234560"
                        },
                        new
                        {
                            CustomerId = 6,
                            Vin = "WVWZZZ3CZWE123461"
                        },
                        new
                        {
                            CustomerId = 7,
                            Vin = "2T1BURHE7JC123462"
                        },
                        new
                        {
                            CustomerId = 8,
                            Vin = "1N4AL3AP9HC123463"
                        },
                        new
                        {
                            CustomerId = 9,
                            Vin = "SALWR2RV7JA123464"
                        },
                        new
                        {
                            CustomerId = 10,
                            Vin = "KMHD84LF5KU123465"
                        });
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("KS_Roles", "dbo");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Technician"
                        });
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("KS_RecallUsers", "dbo");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("KS_UserRoles", "dbo");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecallStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Vin");

                    b.ToTable("KS_Vehicles", "dbo");

                    b.HasData(
                        new
                        {
                            Vin = "1HGCM82633A123456",
                            Make = "Honda",
                            Model = "Accord",
                            RecallStatus = "Open",
                            Year = 2020
                        },
                        new
                        {
                            Vin = "5YFBURHE5FP123457",
                            Make = "Toyota",
                            Model = "Corolla",
                            RecallStatus = "Closed",
                            Year = 2019
                        },
                        new
                        {
                            Vin = "1C4RJFAG5FC123458",
                            Make = "Jeep",
                            Model = "Grand Cherokee",
                            RecallStatus = "Open",
                            Year = 2018
                        },
                        new
                        {
                            Vin = "3FA6P0H76KR123459",
                            Make = "Ford",
                            Model = "Fusion",
                            RecallStatus = "No Recall",
                            Year = 2021
                        },
                        new
                        {
                            Vin = "JM1BL1SF8A1234560",
                            Make = "Mazda",
                            Model = "3",
                            RecallStatus = "Open",
                            Year = 2022
                        },
                        new
                        {
                            Vin = "WVWZZZ3CZWE123461",
                            Make = "Volkswagen",
                            Model = "Jetta",
                            RecallStatus = "Closed",
                            Year = 2017
                        },
                        new
                        {
                            Vin = "2T1BURHE7JC123462",
                            Make = "Toyota",
                            Model = "Camry",
                            RecallStatus = "No Recall",
                            Year = 2020
                        },
                        new
                        {
                            Vin = "1N4AL3AP9HC123463",
                            Make = "Nissan",
                            Model = "Altima",
                            RecallStatus = "Open",
                            Year = 2019
                        },
                        new
                        {
                            Vin = "SALWR2RV7JA123464",
                            Make = "Land Rover",
                            Model = "Range Rover",
                            RecallStatus = "Closed",
                            Year = 2021
                        },
                        new
                        {
                            Vin = "KMHD84LF5KU123465",
                            Make = "Hyundai",
                            Model = "Elantra",
                            RecallStatus = "No Recall",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.RecallCustomerVehicle", b =>
                {
                    b.HasOne("VehicleRecall.Shared.Models.RecallCustomer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRecall.Shared.Models.Vehicle", "Vehicle")
                        .WithMany("CustomerVehicles")
                        .HasForeignKey("Vin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.UserAccount", b =>
                {
                    b.HasOne("VehicleRecall.Shared.Models.RecallCustomer", "Customer")
                        .WithOne("UserAccount")
                        .HasForeignKey("VehicleRecall.Shared.Models.UserAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.UserRole", b =>
                {
                    b.HasOne("VehicleRecall.Shared.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleRecall.Shared.Models.UserAccount", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.RecallCustomer", b =>
                {
                    b.Navigation("UserAccount");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.UserAccount", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("VehicleRecall.Shared.Models.Vehicle", b =>
                {
                    b.Navigation("CustomerVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
